name: lockvet
on:
  pull_request:
    paths:
      - '**/package-lock.json'

permissions:
  pull-requests: write
  contents: read
  security-events: write

jobs:
  lockvet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: matteo-sung/lockvet@v0.1.12
        with:
          sarif: 'true' 
